# Generated by Django 5.1 on 2024-09-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reset_pass_token',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
