# Generated by Django 4.2.7 on 2024-10-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('seller', 'Seller'), ('merchant', 'Merchant')], default=2, max_length=50, verbose_name='User Type'),
            preserve_default=False,
        ),
    ]
