# Generated by Django 5.1 on 2024-09-30 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_coupon', to='orders.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_after_coupon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
