# Generated by Django 5.1 on 2024-10-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_cartdetail_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
