# Generated by Django 5.1 on 2024-10-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderdetail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('InProgress', 'In Progress'), ('Completed', 'Completed')], default='InProgress', max_length=10),
        ),
    ]
