# Generated by Django 5.1 on 2024-09-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='categories/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Desccription'),
        ),
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Feature', 'Feature'), ('Sale', 'Sale')], max_length=10, null=True, verbose_name='Flag'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantitity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantitity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sku'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Subtitle'),
        ),
    ]
